Repository googleapis/python-notebooks, pull requests merged in 2021-04, with the labels that each got.

#29 chore: start tracking obsolete files
  synth.metadata
Labels: api: notebooks, cla: yes, context: full

#30 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: notebooks, automerge, cla: yes, context: full

#31 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: notebooks, cla: yes, context: full, samples

#32 chore: prevent normalization of semver versioning
  setup.py
Labels: api: notebooks, cla: yes

#35 chore(revert): revert preventing normalization
  setup.py
Labels: api: notebooks, cla: yes
